<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetPageProperty("image", SITE_TEMPLATE_PATH."/assets/images/header/06_header.jpg");
$APPLICATION->SetTitle("Контакты");
?>

<?$APPLICATION->IncludeComponent("codekeepers:news.list.justice", "contacts", Array(
	"ACTIVE_DATE_FORMAT" => "d.m.Y",	
		"ADD_SECTIONS_CHAIN" => "N",	
		"AJAX_MODE" => "N",	
		"AJAX_OPTION_ADDITIONAL" => "",	
		"AJAX_OPTION_HISTORY" => "N",	
		"AJAX_OPTION_JUMP" => "N",	
		"AJAX_OPTION_STYLE" => "N",	
		"CACHE_FILTER" => "N",	
		"CACHE_GROUPS" => "Y",	
		"CACHE_TIME" => "36000000",	
		"CACHE_TYPE" => "N",	
		"CHECK_DATES" => "Y",	
		"DETAIL_URL" => "",	
		"DISPLAY_BOTTOM_PAGER" => "N",	
		"DISPLAY_DATE" => "N",	
		"DISPLAY_NAME" => "N",	
		"DISPLAY_PICTURE" => "N",	
		"DISPLAY_PREVIEW_TEXT" => "N",	
		"DISPLAY_TOP_PAGER" => "N",	
		"FIELD_CODE" => array(	
			0 => "",
			1 => "",
		),
		"FILTER_NAME" => "",	
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",	
		"IBLOCK_ID" => $GLOBALS["codekeepers_block_id"]["content_contacts_id"],	
		"IBLOCK_TYPE" => "content",	
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",	
		"INCLUDE_SUBSECTIONS" => "N",	
		"MESSAGE_404" => "",	
		"NEWS_COUNT" => "1",	
		"PAGER_BASE_LINK_ENABLE" => "N",	
		"PAGER_DESC_NUMBERING" => "N",	
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",	
		"PAGER_SHOW_ALL" => "N",	
		"PAGER_SHOW_ALWAYS" => "N",	
		"PAGER_TEMPLATE" => ".default",	
		"PAGER_TITLE" => "Новости",	
		"PARENT_SECTION" => "",	
		"PARENT_SECTION_CODE" => "",	
		"PREVIEW_TRUNCATE_LEN" => "",	
		"PROPERTY_CODE" => array(	
			0 => "email",
			1 => "address",
			2 => "title1",
			3 => "title2",
			4 => "title_email",
			5 => "title_address",
			6 => "title_phone",
			7 => "text",
			8 => "phone",
			9 => "[icon_phone]",
			10 => "[icon_email]",
			11 => "[icon_address]",
			12 => "",
		),
		"SET_BROWSER_TITLE" => "N",	
		"SET_LAST_MODIFIED" => "N",	
		"SET_META_DESCRIPTION" => "N",	
		"SET_META_KEYWORDS" => "N",	
		"SET_STATUS_404" => "N",	
		"SET_TITLE" => "N",	
		"SHOW_404" => "N",	
		"SORT_BY1" => "SORT",	
		"SORT_BY2" => "",	
		"SORT_ORDER1" => "ASC",	
		"SORT_ORDER2" => "",	
		"STRICT_SECTION_CHECK" => "N",	
	),
	false
);?>

<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>